/*
 * This class create a JFileChooser interface to retreive a folder path selected from the user
 */

package freezingvideo;

import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * @authors G. Allegretta, F. Scarangella
 */

public class FolderPathChooser extends JFrame {

    private File pathF;
    private int res;
    JFileChooser folderChooser = new JFileChooser();
    
    public FolderPathChooser() {
        initComponents();
        
        // set a name title to the showed window
        folderChooser.setDialogTitle("Choose a folder");
        // set what kind of element will be retrieved
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // check file result       
        res = folderChooser.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION)
            {
                pathF = folderChooser.getSelectedFile();
                if (pathF.exists()) {
                    // do nothing
                }else {
                    // if the file doesn't exist, show a warning message
                    JOptionPane.showMessageDialog(null, "You must select an existing folder!", "Warning!", JOptionPane.WARNING_MESSAGE);
                    pathF = null;
                }                
            }
    }
    
    // return the folder path as a string
    public File getPathF() {
        return pathF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FolderPathChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FolderPathChooser.setApproveButtonToolTipText("");
        FolderPathChooser.setCurrentDirectory(new java.io.File("C:\\Users\\G\\Videos"));
        FolderPathChooser.setDialogTitle("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FolderPathChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FolderPathChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FolderPathChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FolderPathChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FolderPathChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FolderPathChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FolderPathChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FolderPathChooser;
    // End of variables declaration//GEN-END:variables
}
