/*
 * This class will perform the main interface of the program
 * It will contain just two button, one to lauch the freezing method, the other one to lauch to unfreezing method. 
 */

package freezingvideo;

import javax.swing.JFrame;
import java.net.URL;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * @author G. Allegretta, F. Scarangella
 */

public class FreezingVideoUI extends JFrame {

    // Create a new form FreezingVideoUI
    public FreezingVideoUI() {
        //set form title
        super("Freezing Video");
        //set icon image
        URL icon_URL = getClass().getResource("/images/snow-icon.png");
        Image icon = new ImageIcon(icon_URL).getImage();
        setIconImage(icon);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public static void main(String args[]) {
            FreezingVideoUI window = new FreezingVideoUI();
            window.setSize(350,200);
            // choose what to do when window is closed
            window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            window.setVisible(true);
            // centerize window on screen
            window.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
