/*
 * This class create a JFileChooser interface to retreive the video path selected from the user
 */

package freezingvideo;

import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 * @authors G. Allegretta, F. Scarangella
 */

public class VideoFileChooser extends JFrame {

    private File pathV;
    private int res;
    JFileChooser videoChooser = new JFileChooser();
    
    public VideoFileChooser() {
        initComponents();
        // set a name title to the showed window
        videoChooser.setDialogTitle("Choose a video file");
        // set what kind of element will be retrieved
        videoChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        // set to false the option "tutti i file" for the file type
        videoChooser.setAcceptAllFileFilterUsed(false);
        // create filters that allow only to open video files        
        setFilters(videoChooser);
        // check file result       
        res = videoChooser.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION)
            {
                pathV = videoChooser.getSelectedFile();
                if (pathV.exists()) {
                    // do nothing
                }else {
                    // if the file doesn't exist, show a warning message
                    JOptionPane.showMessageDialog(null, "You must select an existing file!", "Warning!", JOptionPane.WARNING_MESSAGE);
                    pathV = null;
                }                
            }
    }
    
    // return the video path as a string
    public File getPathV() {
        return pathV;
    }
    
    // set filters for the FileChooser
    private static void setFilters(JFileChooser jfc) {
        // define filters to be used
        FileFilter mp4Filter = new FileTypeFilter(".mp4","MP4 Video File");
        FileFilter aviFilter = new FileTypeFilter(".avi","AVI Video File");
        FileFilter wmvFilter = new FileTypeFilter(".wmv","WMV Video File");
        FileFilter mkvFilter = new FileTypeFilter(".mkv","MKV Video File");
        FileFilter mpegFilter = new FileTypeFilter(".mpg","MPEG Video File");
        FileFilter vobFilter = new FileTypeFilter(".vob","VOB Video File");
        FileFilter movFilter = new FileTypeFilter(".mov","MOV Video File");
        FileFilter flvFilter = new FileTypeFilter(".flv","FLV Video File");
        FileFilter gifFilter = new FileTypeFilter(".gif","GIF Video File");
        // set these filters in the JFileChooser interface
        jfc.addChoosableFileFilter(mp4Filter);
        jfc.addChoosableFileFilter(aviFilter);
        jfc.addChoosableFileFilter(wmvFilter);
        jfc.addChoosableFileFilter(mkvFilter);
        jfc.addChoosableFileFilter(mpegFilter);
        jfc.addChoosableFileFilter(vobFilter);
        jfc.addChoosableFileFilter(movFilter);
        jfc.addChoosableFileFilter(flvFilter);
        jfc.addChoosableFileFilter(gifFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VideoFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VideoFileChooser.setApproveButtonText("Open");
        VideoFileChooser.setApproveButtonToolTipText("");
        VideoFileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\G\\Videos"));
        VideoFileChooser.setDialogTitle("Choose a video file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VideoFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VideoFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VideoFileChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser VideoFileChooser;
    // End of variables declaration//GEN-END:variables
}
